In [1]:
import numpy as a

In [20]:
arr1=a.array([1,3,2,4,9])
arr2=a.ones(5)
arr3=a.zeros(3)

In [21]:
arr4=a.concatenate([arr1,arr2,arr3])
arr4

array([1., 3., 2., 4., 9., 1., 1., 1., 1., 1., 0., 0., 0.])

#### 更改arr1 对arr1进行排序

In [25]:
arr1.sort()
arr1

array([1, 2, 3, 4, 9])

#### 用两种方法输出arr1中第三个元素

In [24]:
print(arr1[2])
print(arr1[-3])

3
3


#### 输出从arr1第二个元素到第四个元素组成的数组

In [49]:
arr1[1:4]

array([2, 3, 4])

#### 输出arr1和arr2同位元素相加后得到的数组

In [48]:
arr1 + arr2

array([ 2.,  3.,  4.,  5., 10.])

#### 输出arr1各个元素乘以-5后组成的数组

In [47]:
arr1 * -5

array([ -5, -10, -15, -20, -45])

#### 输出arr1的最大值、最小值、总和、平均值 $(直接运行只会输出最后一行计算结果，要给每个式子加上print）$

In [53]:
print(arr1.max())
print(arr1.min())
print(arr1.sum())
print(arr1.mean())

9
1
19
3.8


#### 用列表的形式能够把符合条件的数组元素取出，如果不加则会只输出布尔值（即：判断各元素是否符合括号内条件）

In [63]:
arr1[(arr1 < 1) | (arr1 > 3)] 

array([4, 9])