In [1]:
import numpy as a

#### 定义创建数组

In [2]:
arr1=a.array([6,2,-7,2,8,-2,1])
arr1

array([ 6,  2, -7,  2,  8, -2,  1])

In [4]:
arr2=a.array([[1,3,5],[2,4,6]])
arr2

array([[1, 3, 5],
       [2, 4, 6]])

#### 打印数组的各项数据

In [17]:
print(arr1.ndim)
print(arr2.ndim)
print(arr1.shape)
print(arr2.shape)
print(arr1.size)
print(arr2.size)
print(arr1.dtype)
print(arr2.dtype)

1
2
(7,)
(2, 3)
7
6
int64
int64


#### 创建数组

In [21]:
a_all_0=a.zeros(6)
a_all_0

array([0., 0., 0., 0., 0., 0.])

In [20]:
a_all_1=a.ones(6)
a_all_1

array([1., 1., 1., 1., 1., 1.])

#### 数组range方法

In [19]:
a_even=a.arange(10,21,2)
a_even

array([10, 12, 14, 16, 18, 20])